//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_information_issue_daily_report
    {
        public int ID { get; set; }
        public string BIZ { get; set; }
        public string PROCESS { get; set; }
        public string MATCODE { get; set; }
        public string ITEM_NUMBER { get; set; }
        public string MATNAME { get; set; }
        public string MATGROUP { get; set; }
        public string COST_CENTER { get; set; }
        public string CAT_TYPE { get; set; }
        public string GAP_QTY { get; set; }
        public string GAP_AMOUNTH { get; set; }
        public string ACTUAL_ISSUE { get; set; }
        public string GAP { get; set; }
        public string MONTHLY_ISSUE { get; set; }
        public string DAILY_ISSUE { get; set; }
        public string GAP_QTY_DAILY { get; set; }
        public string GAP_AMOUNT_DAILY { get; set; }
        public string GAP_DAILY { get; set; }
        public string EXPENSE_MONTHLY { get; set; }
        public string EXPENSE_DAILY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public string LAST_UPDATE_BY { get; set; }
    }
}
