//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_member_Inline
    {
        public int id { get; set; }
        public string GOALBAL_ID { get; set; }
        public string LOCAL_ID { get; set; }
        public string NAME_ENG { get; set; }
        public string SURENAME_ENG { get; set; }
        public string NAME_THAI { get; set; }
        public string SURENAME_THAI { get; set; }
        public string ORGANIZE { get; set; }
        public string POSITION { get; set; }
        public string PERMISSION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string PASSWORD { get; set; }
        public string CREATE_BY { get; set; }
        public string STATUS { get; set; }
        public string Level { get; set; }
    }
}
