//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Master_cut_off
    {
        public int ID_SC { get; set; }
        public string SC_DATE { get; set; }
        public Nullable<System.DateTime> SC_CREATE_DATE { get; set; }
        public string SC_CREATE_BY { get; set; }
        public Nullable<System.DateTime> SC_UPDATE_DATE { get; set; }
        public string SC_UPDATE_BY { get; set; }
        public Nullable<int> SC_STATUS { get; set; }
    }
}
