//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NEvent
    {
        public int id { get; set; }
        public string BIZ_NAME { get; set; }
        public string BIZ_PROCESS { get; set; }
        public string MATCODE { get; set; }
        public string ITEM_NUMBER { get; set; }
        public string MATNAME { get; set; }
        public string MATGROUP { get; set; }
        public string COST_CENTER { get; set; }
        public string STOCK_WH { get; set; }
        public string FLAG_MAT { get; set; }
        public Nullable<int> ISSUE_WH { get; set; }
        public Nullable<int> ISSUE_TARGET { get; set; }
        public Nullable<int> USAGE { get; set; }
        public Nullable<int> REMAIN_INLINE { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public string PURPOSE_DETAIL { get; set; }
        public Nullable<System.DateTime> CUR_DATE { get; set; }
    }
}
