//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Ntransaction
    {
        public int MAT_ID { get; set; }
        public string MATCODE { get; set; }
        public string ITEM_NUMBER { get; set; }
        public string FLAG_MAT { get; set; }
        public Nullable<int> STOCK_WH { get; set; }
        public Nullable<int> ISSUE_WH { get; set; }
        public string COST_CENTER { get; set; }
        public Nullable<double> USAGE { get; set; }
        public Nullable<int> REMAIN_INLINE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public string PURPOSE_DETAIL { get; set; }
        public Nullable<System.DateTime> DATE_FORMATS { get; set; }
        public string MC_ID { get; set; }
        public string REASON_ADJUST_EOMONTH { get; set; }
        public Nullable<System.DateTime> REASON_ADJUST_UPDATE_DATE { get; set; }
    }
}
