//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NEvent_ASSY
    {
        public int ID { get; set; }
        public string BIZ_NAME { get; set; }
        public string PROCESS { get; set; }
        public string MATCODE { get; set; }
        public string ITEM_NUMBER { get; set; }
        public string MATNAME { get; set; }
        public string MATGROUP { get; set; }
        public string COST_CENTER { get; set; }
        public string FLAG_MAT { get; set; }
        public Nullable<double> STOCK_WH { get; set; }
        public Nullable<double> ISSUE_WH { get; set; }
        public Nullable<double> ISSUE_TARGET { get; set; }
        public Nullable<double> USAGE { get; set; }
        public Nullable<double> REMAIN_INLINE { get; set; }
        public string UNIT { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public string PURPOSE_DETAIL { get; set; }
        public Nullable<System.DateTime> CUR_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_USAGE { get; set; }
        public string MC_ID { get; set; }
        public Nullable<System.DateTime> ISSUE_UPDATE_DATE { get; set; }
        public Nullable<double> ADJUST_VALUE { get; set; }
        public string ADJUST_REASON { get; set; }
        public Nullable<System.DateTime> ADJUST_REASON_UPDATE_DATE { get; set; }
        public string COMMENT_AJDSUST_EOMONTH { get; set; }
        public Nullable<System.DateTime> COMMENT_UPDATE_DATE { get; set; }
        public Nullable<double> REMAIN_INLINE_PROBLEM { get; set; }
        public Nullable<System.DateTime> REMAIN_INLINE_PROBLEM_UPDATE_DATE { get; set; }
        public string CAT_TYPE { get; set; }
    }
}
