//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_std_cost_upload
    {
        public int ID { get; set; }
        public string ITEM_NUMBER { get; set; }
        public string DESCRIPTION { get; set; }
        public string CATEGORY { get; set; }
        public string TERM { get; set; }
        public string UNIT_PRICE_CURRENCY { get; set; }
        public string CURRENCY { get; set; }
        public string UNIT_PRICE_TH { get; set; }
        public string FREIGHT { get; set; }
        public string INCURANCE { get; set; }
        public string OVER_HEAD { get; set; }
        public string ITEM_COST_TH { get; set; }
        public string BIZ { get; set; }
        public string MAT_GROUP { get; set; }
        public string S_NAME { get; set; }
        public string M_NAME { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
