//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_temp_data_assy
    {
        public int ID { get; set; }
        public string MATCODE { get; set; }
        public string MATGROUP { get; set; }
        public string ITEM_NUMBER { get; set; }
        public string MATNAME { get; set; }
        public string COST_CENTER { get; set; }
        public string CAT_TYPE { get; set; }
        public string UNIT { get; set; }
        public string QAH_SCT_QA { get; set; }
        public string DRT_HLD_SO_QA { get; set; }
        public string PM_2G_MFG { get; set; }
        public string DRT_2G2_FL_MFG { get; set; }
        public string FLOOR_ACT { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public string PARENT_MAT { get; set; }
        public string FLAG_MAT { get; set; }
    }
}
