//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_temp_junb_csat_target
    {
        public int ID { get; set; }
        public string PROCESS { get; set; }
        public string ITEM_NUMBER { get; set; }
        public string MATERGROUP { get; set; }
        public string MATERIAL_TYPE { get; set; }
        public string COST_CENTER { get; set; }
        public string ISSUE_TARGET { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public string FLAG_MAT { get; set; }
    }
}
