//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_wh_std_pack
    {
        public int ID { get; set; }
        public string MATCODE { get; set; }
        public Nullable<int> QTY_WH { get; set; }
        public string MATGROUP { get; set; }
    }
}
