//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDailyPlan
    {
        public string Biz { get; set; }
        public string MC_Name { get; set; }
        public string Item_Name { get; set; }
        public string Product_Group { get; set; }
        public string Process { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<long> Input { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public string TB { get; set; }
    }
}
