//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_REQUEST_MAT_HISTORY
    {
        public decimal ROW_ID { get; set; }
        public string REQUISITION_ID { get; set; }
        public string MATCODE { get; set; }
        public string MATNAME { get; set; }
        public string REQ_QTY { get; set; }
        public string REQ_UOM { get; set; }
        public string COST_CENTER { get; set; }
        public string COST_CENTER_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public string USE_DATE { get; set; }
        public string URGENT_STATUS { get; set; }
        public string RESON_REQUEST { get; set; }
        public string LOT { get; set; }
        public string REMARK_MANUAL { get; set; }
    }
}
