//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_miscell_summary_email_is
    {
        public int ID { get; set; }
        public string BIZ { get; set; }
        public string PROCESS { get; set; }
        public string MATCODE { get; set; }
        public string ITEM_NUMBER { get; set; }
        public string MATNAME { get; set; }
        public string MATGROUP { get; set; }
        public string COST_CENTER { get; set; }
        public string CAT_TYPE { get; set; }
        public string GAP_QTY { get; set; }
        public string GAP_AMOUNTH { get; set; }
    }
}
