//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_test
    {
        public string OPE_NAME { get; set; }
        public string LOC_NAME { get; set; }
        public string MAC_ID { get; set; }
        public string PARTS_CD { get; set; }
        public Nullable<decimal> USE_QTY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
    }
}
