//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inlineStock_rs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwV_RECEIPT
    {
        public string BIZ_NAME { get; set; }
        public string MATCODE { get; set; }
        public string ITEM_NUMBER { get; set; }
        public string MATNAME { get; set; }
        public string MATGROUP { get; set; }
        public Nullable<double> PO_LT { get; set; }
        public Nullable<double> MOQ { get; set; }
        public Nullable<double> SAFETY_STOCK { get; set; }
        public Nullable<double> STD_PACK { get; set; }
        public string UOM { get; set; }
        public string MAKER_NAME { get; set; }
        public string STATUS { get; set; }
    }
}
